
export interface AppTheme {
  id: string;
  name: string;
  description: string;
  forcedMode?: 'light' | 'dark';
  colors: {
    background: string;
    text: string;
    textSecondary: string;
    primary: string;
    secondary: string;
    accent: string;
    card: string;
    highlight: string;
    border: string;
    error: string;
    success: string;
    warning: string;
    gold: string;
  };
  fontFamily?: string;
  borderRadius?: number;
  pixelated?: boolean;
  isDefault?: boolean;
}

export const APP_THEMES: AppTheme[] = [
  {
    id: 'default',
    name: 'Default',
    description: 'Clean and modern forest theme with adaptive light/dark mode',
    isDefault: true,
    colors: {
      background: '#F0F4F7',
      text: '#2D3436',
      textSecondary: '#747A7C',
      primary: '#3498DB',
      secondary: '#2ECC71',
      accent: '#F39C12',
      card: '#FFFFFF',
      highlight: '#EBF5FB',
      border: '#E0E0E0',
      error: '#E74C3C',
      success: '#27AE60',
      warning: '#F39C12',
      gold: '#FFD700',
    },
  },
  {
    id: 'ocean-breeze',
    name: 'Ocean Breeze',
    description: 'Cool blue tones inspired by the sea',
    forcedMode: 'light',
    colors: {
      background: '#E8F4F8',
      text: '#1B4965',
      textSecondary: '#5FA8D3',
      primary: '#1B4965',
      secondary: '#62B6CB',
      accent: '#BEE9E8',
      card: '#FFFFFF',
      highlight: '#CAE9FF',
      border: '#BEE9E8',
      error: '#E63946',
      success: '#06D6A0',
      warning: '#FFB703',
      gold: '#FFD700',
    },
  },
  {
    id: 'ocean-breeze-dark',
    name: 'Ocean Breeze Dark',
    description: 'Cool blue tones in dark mode',
    forcedMode: 'dark',
    colors: {
      background: '#0D1B2A',
      text: '#E8F4F8',
      textSecondary: '#87CEEB',
      primary: '#62B6CB',
      secondary: '#BEE9E8',
      accent: '#CAE9FF',
      card: '#1B263B',
      highlight: '#2A3F5F',
      border: '#415A77',
      error: '#E63946',
      success: '#06D6A0',
      warning: '#FFB703',
      gold: '#FFD700',
    },
  },
  {
    id: 'sunset-glow',
    name: 'Sunset Glow',
    description: 'Warm sunset colors',
    forcedMode: 'light',
    colors: {
      background: '#FFF5E6',
      text: '#5D2E46',
      textSecondary: '#8B5A7C',
      primary: '#FF6B6B',
      secondary: '#FFB347',
      accent: '#FFA07A',
      card: '#FFFFFF',
      highlight: '#FFE4E1',
      border: '#FFD4B8',
      error: '#DC143C',
      success: '#32CD32',
      warning: '#FFA500',
      gold: '#FFD700',
    },
  },
  {
    id: 'sunset-glow-dark',
    name: 'Sunset Glow Dark',
    description: 'Warm sunset colors in dark mode',
    forcedMode: 'dark',
    colors: {
      background: '#2A1A1F',
      text: '#FFE4E1',
      textSecondary: '#D4A5A5',
      primary: '#FF6B6B',
      secondary: '#FFB347',
      accent: '#FFA07A',
      card: '#3D2A2F',
      highlight: '#4D3A3F',
      border: '#5D4A4F',
      error: '#DC143C',
      success: '#32CD32',
      warning: '#FFA500',
      gold: '#FFD700',
    },
  },
  {
    id: 'forest-dark',
    name: 'Forest Dark',
    description: 'Deep forest night theme',
    forcedMode: 'dark',
    colors: {
      background: '#0D1B2A',
      text: '#E0E1DD',
      textSecondary: '#A0A8B0',
      primary: '#778DA9',
      secondary: '#415A77',
      accent: '#8FA8C0',
      card: '#1B263B',
      highlight: '#2A3F5F',
      border: '#415A77',
      error: '#E63946',
      success: '#06D6A0',
      warning: '#FFB703',
      gold: '#FFD700',
    },
  },
  {
    id: 'neon-nights',
    name: 'Neon Nights',
    description: 'Vibrant neon cyberpunk style',
    forcedMode: 'dark',
    colors: {
      background: '#0A0E27',
      text: '#F0F0F0',
      textSecondary: '#C0C0D1',
      primary: '#FF006E',
      secondary: '#8338EC',
      accent: '#3A86FF',
      card: '#1A1F3A',
      highlight: '#2A2F4A',
      border: '#FF006E',
      error: '#FF0000',
      success: '#00FF00',
      warning: '#FFFF00',
      gold: '#FFD700',
    },
  },
  {
    id: 'earthy-tones',
    name: 'Earthy Tones',
    description: 'Natural earth colors',
    forcedMode: 'light',
    colors: {
      background: '#F5F1E8',
      text: '#3E2723',
      textSecondary: '#6D4C41',
      primary: '#8D6E63',
      secondary: '#A1887F',
      accent: '#BCAAA4',
      card: '#FFFFFF',
      highlight: '#EFEBE9',
      border: '#D7CCC8',
      error: '#D32F2F',
      success: '#388E3C',
      warning: '#F57C00',
      gold: '#FFD700',
    },
  },
  {
    id: 'earthy-tones-dark',
    name: 'Earthy Tones Dark',
    description: 'Natural earth colors in dark mode',
    forcedMode: 'dark',
    colors: {
      background: '#2A1F1A',
      text: '#EFEBE9',
      textSecondary: '#A1887F',
      primary: '#BCAAA4',
      secondary: '#D7CCC8',
      accent: '#E0D5D0',
      card: '#3E2F2A',
      highlight: '#4E3F3A',
      border: '#6D4C41',
      error: '#D32F2F',
      success: '#388E3C',
      warning: '#F57C00',
      gold: '#FFD700',
    },
  },
  {
    id: 'arctic-frost',
    name: 'Arctic Frost',
    description: 'Cool icy winter theme',
    forcedMode: 'light',
    colors: {
      background: '#E8F4F8',
      text: '#1C3144',
      textSecondary: '#5C7A99',
      primary: '#4A90A4',
      secondary: '#87CEEB',
      accent: '#B0E0E6',
      card: '#FFFFFF',
      highlight: '#F0F8FF',
      border: '#ADD8E6',
      error: '#DC143C',
      success: '#20B2AA',
      warning: '#FFB347',
      gold: '#FFD700',
    },
  },
  {
    id: 'arctic-frost-dark',
    name: 'Arctic Frost Dark',
    description: 'Cool icy winter theme in dark mode',
    forcedMode: 'dark',
    colors: {
      background: '#0F1C2A',
      text: '#F0F8FF',
      textSecondary: '#87CEEB',
      primary: '#87CEEB',
      secondary: '#B0E0E6',
      accent: '#D0F0F6',
      card: '#1C2F44',
      highlight: '#2A3F5F',
      border: '#4A90A4',
      error: '#DC143C',
      success: '#20B2AA',
      warning: '#FFB347',
      gold: '#FFD700',
    },
  },
  {
    id: 'cherry-blossom',
    name: 'Cherry Blossom',
    description: 'Soft pink spring theme',
    forcedMode: 'light',
    colors: {
      background: '#FFF0F5',
      text: '#4A2C2A',
      textSecondary: '#8B6F6F',
      primary: '#FF69B4',
      secondary: '#FFB6C1',
      accent: '#FFC0CB',
      card: '#FFFFFF',
      highlight: '#FFE4E1',
      border: '#FFB6C1',
      error: '#DC143C',
      success: '#32CD32',
      warning: '#FFA500',
      gold: '#FFD700',
    },
  },
  {
    id: 'cherry-blossom-dark',
    name: 'Cherry Blossom Dark',
    description: 'Soft pink spring theme in dark mode',
    forcedMode: 'dark',
    colors: {
      background: '#2A1A1F',
      text: '#FFE4E1',
      textSecondary: '#D4A5A5',
      primary: '#FF69B4',
      secondary: '#FFB6C1',
      accent: '#FFC0CB',
      card: '#3D2A2F',
      highlight: '#4D3A3F',
      border: '#8B6F6F',
      error: '#DC143C',
      success: '#32CD32',
      warning: '#FFA500',
      gold: '#FFD700',
    },
  },
  {
    id: 'midnight-purple',
    name: 'Midnight Purple',
    description: 'Deep purple night theme',
    forcedMode: 'dark',
    colors: {
      background: '#1A0B2E',
      text: '#E8DFF5',
      textSecondary: '#B0A0D4',
      primary: '#7B2CBF',
      secondary: '#9D4EDD',
      accent: '#C77DFF',
      card: '#2D1B4E',
      highlight: '#3E2A5E',
      border: '#7B2CBF',
      error: '#FF006E',
      success: '#06FFA5',
      warning: '#FFD60A',
      gold: '#FFD700',
    },
  },
  {
    id: 'autumn-harvest',
    name: 'Autumn Harvest',
    description: 'Warm autumn colors',
    forcedMode: 'light',
    colors: {
      background: '#FFF8E7',
      text: '#5D3A1A',
      textSecondary: '#8B6F47',
      primary: '#D2691E',
      secondary: '#CD853F',
      accent: '#DEB887',
      card: '#FFFFFF',
      highlight: '#FAEBD7',
      border: '#D2B48C',
      error: '#DC143C',
      success: '#228B22',
      warning: '#FF8C00',
      gold: '#FFD700',
    },
  },
  {
    id: 'autumn-harvest-dark',
    name: 'Autumn Harvest Dark',
    description: 'Warm autumn colors in dark mode',
    forcedMode: 'dark',
    colors: {
      background: '#2A1F0F',
      text: '#FAEBD7',
      textSecondary: '#D2B48C',
      primary: '#DEB887',
      secondary: '#F4A460',
      accent: '#FFE4B5',
      card: '#3D2F1F',
      highlight: '#4D3F2F',
      border: '#8B6F47',
      error: '#DC143C',
      success: '#228B22',
      warning: '#FF8C00',
      gold: '#FFD700',
    },
  },
  {
    id: 'tropical-paradise',
    name: 'Tropical Paradise',
    description: 'Vibrant tropical colors',
    forcedMode: 'light',
    colors: {
      background: '#F0FFF0',
      text: '#2F4F2F',
      textSecondary: '#556B2F',
      primary: '#00CED1',
      secondary: '#FF6347',
      accent: '#FFD700',
      card: '#FFFFFF',
      highlight: '#E0FFFF',
      border: '#98FB98',
      error: '#DC143C',
      success: '#32CD32',
      warning: '#FFA500',
      gold: '#FFD700',
    },
  },
  {
    id: 'tropical-paradise-dark',
    name: 'Tropical Paradise Dark',
    description: 'Vibrant tropical colors in dark mode',
    forcedMode: 'dark',
    colors: {
      background: '#1F2F1F',
      text: '#E0FFFF',
      textSecondary: '#98FB98',
      primary: '#00CED1',
      secondary: '#FF6347',
      accent: '#FFD700',
      card: '#2F3F2F',
      highlight: '#3F4F3F',
      border: '#556B2F',
      error: '#DC143C',
      success: '#32CD32',
      warning: '#FFA500',
      gold: '#FFD700',
    },
  },
  {
    id: 'desert-sand',
    name: 'Desert Sand',
    description: 'Warm desert landscape',
    forcedMode: 'light',
    colors: {
      background: '#FFF8DC',
      text: '#8B4513',
      textSecondary: '#A0522D',
      primary: '#CD853F',
      secondary: '#DAA520',
      accent: '#F4A460',
      card: '#FFFFFF',
      highlight: '#FFEFD5',
      border: '#DEB887',
      error: '#DC143C',
      success: '#228B22',
      warning: '#FF8C00',
      gold: '#FFD700',
    },
  },
  {
    id: 'desert-sand-dark',
    name: 'Desert Sand Dark',
    description: 'Warm desert landscape in dark mode',
    forcedMode: 'dark',
    colors: {
      background: '#2B1F0F',
      text: '#FFEFD5',
      textSecondary: '#DEB887',
      primary: '#F4A460',
      secondary: '#DAA520',
      accent: '#FFE4B5',
      card: '#3B2F1F',
      highlight: '#4B3F2F',
      border: '#A0522D',
      error: '#DC143C',
      success: '#228B22',
      warning: '#FF8C00',
      gold: '#FFD700',
    },
  },
  {
    id: 'lavender-fields',
    name: 'Lavender Fields',
    description: 'Soft purple and lavender tones',
    forcedMode: 'light',
    colors: {
      background: '#F8F4FF',
      text: '#4B0082',
      textSecondary: '#8B7BA8',
      primary: '#9370DB',
      secondary: '#BA55D3',
      accent: '#DDA0DD',
      card: '#FFFFFF',
      highlight: '#E6E6FA',
      border: '#D8BFD8',
      error: '#DC143C',
      success: '#32CD32',
      warning: '#FFA500',
      gold: '#FFD700',
    },
  },
  {
    id: 'lavender-fields-dark',
    name: 'Lavender Fields Dark',
    description: 'Soft purple and lavender tones in dark mode',
    forcedMode: 'dark',
    colors: {
      background: '#1F1A2E',
      text: '#E6E6FA',
      textSecondary: '#D8BFD8',
      primary: '#BA55D3',
      secondary: '#DDA0DD',
      accent: '#EE82EE',
      card: '#2F2A3E',
      highlight: '#3F3A4E',
      border: '#8B7BA8',
      error: '#DC143C',
      success: '#32CD32',
      warning: '#FFA500',
      gold: '#FFD700',
    },
  },
  {
    id: 'mint-fresh',
    name: 'Mint Fresh',
    description: 'Cool mint and green tones',
    forcedMode: 'light',
    colors: {
      background: '#F0FFF4',
      text: '#2F4F4F',
      textSecondary: '#5F9EA0',
      primary: '#3CB371',
      secondary: '#66CDAA',
      accent: '#98FB98',
      card: '#FFFFFF',
      highlight: '#E0FFF0',
      border: '#B0E0B0',
      error: '#DC143C',
      success: '#32CD32',
      warning: '#FFA500',
      gold: '#FFD700',
    },
  },
  {
    id: 'mint-fresh-dark',
    name: 'Mint Fresh Dark',
    description: 'Cool mint and green tones in dark mode',
    forcedMode: 'dark',
    colors: {
      background: '#1F2F2F',
      text: '#E0FFF0',
      textSecondary: '#B0E0B0',
      primary: '#66CDAA',
      secondary: '#98FB98',
      accent: '#B0FFB0',
      card: '#2F3F3F',
      highlight: '#3F4F4F',
      border: '#5F9EA0',
      error: '#DC143C',
      success: '#32CD32',
      warning: '#FFA500',
      gold: '#FFD700',
    },
  },
  {
    id: 'coral-reef',
    name: 'Coral Reef',
    description: 'Vibrant coral and ocean colors',
    forcedMode: 'light',
    colors: {
      background: '#FFF5EE',
      text: '#8B4513',
      textSecondary: '#CD5C5C',
      primary: '#FF7F50',
      secondary: '#FA8072',
      accent: '#FFA07A',
      card: '#FFFFFF',
      highlight: '#FFE4E1',
      border: '#FFB6C1',
      error: '#DC143C',
      success: '#32CD32',
      warning: '#FFA500',
      gold: '#FFD700',
    },
  },
  {
    id: 'coral-reef-dark',
    name: 'Coral Reef Dark',
    description: 'Vibrant coral and ocean colors in dark mode',
    forcedMode: 'dark',
    colors: {
      background: '#2B1F1A',
      text: '#FFE4E1',
      textSecondary: '#FFB6C1',
      primary: '#FF7F50',
      secondary: '#FA8072',
      accent: '#FFA07A',
      card: '#3B2F2A',
      highlight: '#4B3F3A',
      border: '#CD5C5C',
      error: '#DC143C',
      success: '#32CD32',
      warning: '#FFA500',
      gold: '#FFD700',
    },
  },
  {
    id: 'slate-gray',
    name: 'Slate Gray',
    description: 'Professional gray tones',
    forcedMode: 'light',
    colors: {
      background: '#F5F5F5',
      text: '#2F4F4F',
      textSecondary: '#708090',
      primary: '#4682B4',
      secondary: '#5F9EA0',
      accent: '#87CEEB',
      card: '#FFFFFF',
      highlight: '#E8E8E8',
      border: '#D3D3D3',
      error: '#DC143C',
      success: '#32CD32',
      warning: '#FFA500',
      gold: '#FFD700',
    },
  },
  {
    id: 'slate-gray-dark',
    name: 'Slate Gray Dark',
    description: 'Professional gray tones in dark mode',
    forcedMode: 'dark',
    colors: {
      background: '#1F2F2F',
      text: '#E8E8E8',
      textSecondary: '#D3D3D3',
      primary: '#87CEEB',
      secondary: '#5F9EA0',
      accent: '#B0C4DE',
      card: '#2F3F3F',
      highlight: '#3F4F4F',
      border: '#708090',
      error: '#DC143C',
      success: '#32CD32',
      warning: '#FFA500',
      gold: '#FFD700',
    },
  },
  {
    id: 'golden-hour',
    name: 'Golden Hour',
    description: 'Warm golden sunset tones',
    forcedMode: 'light',
    colors: {
      background: '#FFFAF0',
      text: '#8B4513',
      textSecondary: '#CD853F',
      primary: '#FFD700',
      secondary: '#FFA500',
      accent: '#FF8C00',
      card: '#FFFFFF',
      highlight: '#FFF8DC',
      border: '#FFE4B5',
      error: '#DC143C',
      success: '#32CD32',
      warning: '#FFA500',
      gold: '#FFD700',
    },
  },
  {
    id: 'golden-hour-dark',
    name: 'Golden Hour Dark',
    description: 'Warm golden sunset tones in dark mode',
    forcedMode: 'dark',
    colors: {
      background: '#2B1F0A',
      text: '#FFF8DC',
      textSecondary: '#FFE4B5',
      primary: '#FFD700',
      secondary: '#FFA500',
      accent: '#FF8C00',
      card: '#3B2F1A',
      highlight: '#4B3F2A',
      border: '#CD853F',
      error: '#DC143C',
      success: '#32CD32',
      warning: '#FFA500',
      gold: '#FFD700',
    },
  },
  {
    id: 'rose-garden',
    name: 'Rose Garden',
    description: 'Romantic rose and pink tones',
    forcedMode: 'light',
    colors: {
      background: '#FFF0F5',
      text: '#8B0A50',
      textSecondary: '#C71585',
      primary: '#FF1493',
      secondary: '#FF69B4',
      accent: '#FFB6C1',
      card: '#FFFFFF',
      highlight: '#FFE4E1',
      border: '#FFC0CB',
      error: '#DC143C',
      success: '#32CD32',
      warning: '#FFA500',
      gold: '#FFD700',
    },
  },
  {
    id: 'rose-garden-dark',
    name: 'Rose Garden Dark',
    description: 'Romantic rose and pink tones in dark mode',
    forcedMode: 'dark',
    colors: {
      background: '#2A0A1F',
      text: '#FFE4E1',
      textSecondary: '#FFC0CB',
      primary: '#FF1493',
      secondary: '#FF69B4',
      accent: '#FFB6C1',
      card: '#3A1A2F',
      highlight: '#4A2A3F',
      border: '#C71585',
      error: '#DC143C',
      success: '#32CD32',
      warning: '#FFA500',
      gold: '#FFD700',
    },
  },
  {
    id: 'emerald-forest',
    name: 'Emerald Forest',
    description: 'Rich emerald green tones',
    forcedMode: 'light',
    colors: {
      background: '#F0FFF0',
      text: '#006400',
      textSecondary: '#228B22',
      primary: '#50C878',
      secondary: '#2E8B57',
      accent: '#3CB371',
      card: '#FFFFFF',
      highlight: '#E0FFE0',
      border: '#90EE90',
      error: '#DC143C',
      success: '#32CD32',
      warning: '#FFA500',
      gold: '#FFD700',
    },
  },
  {
    id: 'emerald-forest-dark',
    name: 'Emerald Forest Dark',
    description: 'Rich emerald green tones in dark mode',
    forcedMode: 'dark',
    colors: {
      background: '#0A1F0A',
      text: '#E0FFE0',
      textSecondary: '#90EE90',
      primary: '#50C878',
      secondary: '#3CB371',
      accent: '#66CDAA',
      card: '#1A2F1A',
      highlight: '#2A3F2A',
      border: '#228B22',
      error: '#DC143C',
      success: '#32CD32',
      warning: '#FFA500',
      gold: '#FFD700',
    },
  },
  {
    id: 'sapphire-sky',
    name: 'Sapphire Sky',
    description: 'Deep sapphire blue tones',
    forcedMode: 'light',
    colors: {
      background: '#F0F8FF',
      text: '#00008B',
      textSecondary: '#4169E1',
      primary: '#0F52BA',
      secondary: '#4682B4',
      accent: '#6495ED',
      card: '#FFFFFF',
      highlight: '#E6F2FF',
      border: '#B0C4DE',
      error: '#DC143C',
      success: '#32CD32',
      warning: '#FFA500',
      gold: '#FFD700',
    },
  },
  {
    id: 'sapphire-sky-dark',
    name: 'Sapphire Sky Dark',
    description: 'Deep sapphire blue tones in dark mode',
    forcedMode: 'dark',
    colors: {
      background: '#0A0F1F',
      text: '#E6F2FF',
      textSecondary: '#B0C4DE',
      primary: '#4682B4',
      secondary: '#6495ED',
      accent: '#87CEEB',
      card: '#1A1F2F',
      highlight: '#2A2F3F',
      border: '#4169E1',
      error: '#DC143C',
      success: '#32CD32',
      warning: '#FFA500',
      gold: '#FFD700',
    },
  },
  {
    id: 'crimson-sunset',
    name: 'Crimson Sunset',
    description: 'Bold crimson and red tones',
    forcedMode: 'light',
    colors: {
      background: '#FFF5F5',
      text: '#8B0000',
      textSecondary: '#B22222',
      primary: '#DC143C',
      secondary: '#FF6347',
      accent: '#FF7F50',
      card: '#FFFFFF',
      highlight: '#FFE4E1',
      border: '#FFB6C1',
      error: '#DC143C',
      success: '#32CD32',
      warning: '#FFA500',
      gold: '#FFD700',
    },
  },
  {
    id: 'crimson-sunset-dark',
    name: 'Crimson Sunset Dark',
    description: 'Bold crimson and red tones in dark mode',
    forcedMode: 'dark',
    colors: {
      background: '#1F0A0A',
      text: '#FFE4E1',
      textSecondary: '#FFB6C1',
      primary: '#DC143C',
      secondary: '#FF6347',
      accent: '#FF7F50',
      card: '#2F1A1A',
      highlight: '#3F2A2A',
      border: '#B22222',
      error: '#DC143C',
      success: '#32CD32',
      warning: '#FFA500',
      gold: '#FFD700',
    },
  },
];
